Repository ManageIQ/manageiq-providers-ibm_terraform, pull requests merged in 2020-11, with the labels that each got.

#44 Remove content runtime templates from discovery
  app/models/manageiq/providers/ibm_terraform/inventory/collector/configuration_manager.rb
  spec/vcr_cassettes/manageiq/providers/ibm_terraform/configuration_manager/refresher.yml
Labels: bug, kasparov/yes?

#46 Add a IBM Terraform vendor icon.
  app/assets/images/svg/vendor-ibm_terraform_configuration.svg
Labels: kasparov/yes?

#47 Update Azure ems_ref to match Azure Provider
  app/models/manageiq/providers/ibm_terraform/inventory/parser/configuration_manager.rb
  app/models/manageiq/providers/ibm_terraform/inventory/persister/configuration_manager.rb
  spec/models/manageiq/providers/ibm_terraform/configuration_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_terraform/configuration_manager/refresher.yml
Labels: kasparov/yes?

#48 Drop gettext initializer
  config/initializers/gettext.rb
Labels: cleanup

#49 Do not memoize the params_for_create to fix the translation issues
  app/models/manageiq/providers/ibm_terraform/provider.rb
Labels: bug, kasparov/yes?

#50 Retrieve hostname with multiple tags
  app/models/manageiq/providers/ibm_terraform/inventory/parser/configuration_manager.rb
  spec/models/manageiq/providers/ibm_terraform/configuration_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_terraform/configuration_manager/refresher.yml
Labels: kasparov/yes?
