Repository ManageIQ/manageiq-providers-ibm_terraform, pull requests merged in 2020-10, with the labels that each got.

#34 Set the hostname for the configured systems
  app/models/manageiq/providers/ibm_terraform/inventory/collector/configuration_manager.rb
  app/models/manageiq/providers/ibm_terraform/inventory/parser/configuration_manager.rb
  spec/models/manageiq/providers/ibm_terraform/configuration_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_terraform/configuration_manager/refresher.yml
Labels: bug

#35 Fix template details link
  app/models/manageiq/providers/ibm_terraform/configuration_manager/configuration_profile.rb
  spec/models/manageiq/providers/ibm_terraform/configuration_manager/refresher_spec.rb
Labels: bug

#37 Add orchestration stacks
  app/models/manageiq/providers/ibm_terraform/configuration_manager.rb
  app/models/manageiq/providers/ibm_terraform/configuration_manager/configured_system.rb
  app/models/manageiq/providers/ibm_terraform/configuration_manager/orchestration_stack.rb
  app/models/manageiq/providers/ibm_terraform/inventory/collector/configuration_manager.rb
  app/models/manageiq/providers/ibm_terraform/inventory/parser/configuration_manager.rb
  app/models/manageiq/providers/ibm_terraform/inventory/persister/configuration_manager.rb
  spec/models/manageiq/providers/ibm_terraform/configuration_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_terraform/configuration_manager/refresher.yml
Labels: enhancement

#38 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test
